# Generates an artifact containing the result of the `yarn compile` command.

name: Generate PR artifact

on:
  pull_request:
    types: [ opened, synchronize ]
  push:
    branches:
      - '*'

permissions:
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  compile:
    runs-on: ubuntu-22.04
    outputs:
      compilation-result: ${{ steps.compilation.outputs.result }}
      check-translation-result: ${{ steps.check-translation.outputs.result }}
      test-url: ${{ steps.set-test-url.outputs.fr }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
          cache: 'yarn'
      - run: yarn install --immutable
      - id: compilation
        run: |
          # Compiles the model and stores the result -- with escaped special characters.
          body="$(yarn compile 2> /dev/null | cat | tail --lines=+3 | head --lines=-1)"
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}"
          echo "::set-output name=result::${body}"
      - id: check-translation
        run: |
          # Checks the rules translation
          body="$(yarn translate:check)"
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}"
          echo "::set-output name=result::${body}"

      - id: set-test-url
        # Setups the NGC url with the corresponding PR number: https://nosgestesclimat.fr?PR=<pr_number>
        run: echo "::set-output name=fr::${{ steps.deploy-env.outputs.name == 'master' && 'https://nosgestesclimat.fr' || format('https://nosgestesclimat.fr?PR={0}', github.event.pull_request.number) }}"

  upload-artifact:
    runs-on: ubuntu-22.04
    needs: compile
    steps:
      - name: Create artifact
        run: |
          mkdir -p artifacts
          echo "
          ## 🚀 The pull request #${{ github.event.pull_request.number }} is open\!
          > Test the model from the website: ${{ needs.compile.outputs.test-url }}

          Current model compilation status:

          \`\`\`
          ${{ needs.compile.outputs.compilation-result }}
          \`\`\`

          Rules translation status:

          \`\`\`
          ${{ needs.compile.outputs.check-translation-result }}
          \`\`\`
          " > artifacts/result.md
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: pr_message
          path: artifacts
